dockerfile and docker compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,43 +1,125 @@
-version: '3'
+x-app-env: &app-env
+  environment:
+    # APP
+    - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
+    - NEXT_PUBLIC_GLEAP_API_KEY=${NEXT_PUBLIC_GLEAP_API_KEY}
+
+    # Payload
+    - DATABASE_URI=${DATABASE_URI}
+    - PAYLOAD_SECRET=${PAYLOAD_SECRET}
+    - SERVER_URL=${SERVER_URL}
+
+    # Brevo
+    - BREVO_SENDER_NAME=${BREVO_SENDER_NAME}
+    - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
+    - BREVO_API_KEY=${BREVO_API_KEY}
+
+    # S3
+    - S3_BUCKET=${S3_BUCKET}
+    - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
+    - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
+    - S3_REGION=${S3_REGION}
+    - S3_ENDPOINT=${S3_ENDPOINT}
+    - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
 
 services:
-  payload:
-    image: node:18-alpine
-    ports:
-      - '3000:3000'
-    volumes:
-      - .:/home/node/app
-      - node_modules:/home/node/app/node_modules
-    working_dir: /home/node/app/
-    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
-    depends_on:
-      - mongo
-      # - postgres
-    env_file:
-      - .env
-
-  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
-  mongo:
-    image: mongo:latest
-    ports:
-      - '27017:27017'
-    command:
-      - --storageEngine=wiredTiger
-    volumes:
-      - data:/data/db
-    logging:
-      driver: none
-
-  # Uncomment the following to use postgres
-  # postgres:
+  # ------------------------------------------
+  # Next.js App
+  # ------------------------------------------
+  # app:
+  #   image: test
   #   restart: always
-  #   image: postgres:latest
-  #   volumes:
-  #     - pgdata:/var/lib/postgresql/data
+  #   healthcheck:
+  #     test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
+  #     interval: 30s
+  #     timeout: 10s
+  #     retries: 3
+  #     start_period: 10s
+  #   env_file:
+  #     - .env
   #   ports:
-  #     - "5432:5432"
+  #     - '3000:3000'
+  #   command: pnpm run start
+
+  # ------------------------------------------
+  # POSTGRES DATABASE
+  # ------------------------------------------
+  postgres:
+    image: postgres:17
+    restart: always
+    environment:
+      - POSTGRES_USER=postgres
+      - POSTGRES_DB=nonanteneuf
+      - POSTGRES_PASSWORD=postgres
+    volumes:
+      - pg_data:/var/lib/postgresql/data
+    healthcheck:
+      test: ['CMD-SHELL', 'pg_isready -U postgres -d nonanteneuf']
+      interval: 5s
+      timeout: 5s
+      retries: 5
+    ports:
+      - '5432:5432'
+    command: ['postgres', '-c', 'wal_level=logical']
+
+  # ------------------------------------------
+  # MINIO SERVER
+  # ------------------------------------------
+  # minio:
+  #   image: minio/minio
+  #   restart: unless-stopped
+  #   ports:
+  #     - '9000:9000'
+  #     - '9001:9001'
+  #   environment:
+  #     MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
+  #     MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
+  #     MINIO_ADDRESS: ':9000'
+  #     MINIO_CONSOLE_ADDRESS: ':9001'
+  #     MC_CONFIG_DIR: '/root/.mc'
+  #   command: server /data --console-address ":9001"
+  #   volumes:
+  #     - minio_data:/data
+  #   healthcheck:
+  #     test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
+  #     interval: 3s
+  #     timeout: 20s
+  #     retries: 3
+
+  # ------------------------------------------
+  # MINIO BUCKET AUTO-CREATOR
+  # ------------------------------------------
+  # createbuckets:
+  #   image: minio/mc
+  #   depends_on:
+  #     minio:
+  #       condition: service_healthy
+  #   entrypoint: >
+  #     /bin/sh -c "
+  #     echo '⏳ Setting up MinIO bucket...';
+  #
+  #     until (/usr/bin/mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY_ID} ${S3_SECRET_ACCESS_KEY}) do
+  #       echo '...waiting for MinIO...' && sleep 1;
+  #     done;
+  #
+  #     if ! /usr/bin/mc ls myminio/${S3_BUCKET}; then
+  #       echo '🚀 Creating bucket: ${S3_BUCKET}';
+  #       /usr/bin/mc mb myminio/${S3_BUCKET};
+  #       /usr/bin/mc anonymous set public myminio/${S3_BUCKET};
+  #     fi;
+  #
+  #     # Service account (same as your old compose)
+  #     if ! /usr/bin/mc admin user svcacct info myminio/ ${S3_ACCESS_KEY_ID}; then
+  #       echo '🔑 Creating service account...';
+  #       /usr/bin/mc admin user svcacct add myminio/ ${S3_ACCESS_KEY_ID} \
+  #         --access-key ${S3_ACCESS_KEY_ID} \
+  #         --secret-key ${S3_SECRET_ACCESS_KEY};
+  #     fi;
+  #
+  #     echo '✅ MinIO bucket + service account ready.';
+  #     exit 0;
+  #     "
 
 volumes:
-  data:
-  # pgdata:
-  node_modules:
+  pg_data:
+  #minio_data:
